### ISSUE TITLE
iPad version?

### ISSUE THREAD

**Issue by gaming-hacker** [kennyledet/SwiftCap#1]
how would i modify the code for iPad?

i've looked through AVCaptureSession.h and don't see anywhere it specifies an iPad device ID.

**Comment by kennyledet** [comment]
Hey, I haven't tested it out on mobile yet, it was built using the OS X SDKs. You can do something similar but it's using a private API. https://github.com/gabriel/CaptureRecord

**Comment by gaming-hacker** [comment]
thanks
ok. apple store doesn't like using private API.
